acc_task_index:
    path:     /index
    defaults: { _controller: ACCUserBundle:Task:index }

acc_task_add:
    path:     /add
    defaults: { _controller: ACCUserBundle:Task:add }

acc_task_create:
    path:     /create
    defaults: { _controller: ACCUserBundle:Task:create }
    methods:  POST

acc_task_edit:
    path:     /edit/{id}
    defaults: { _controller: ACCUserBundle:Task:edit }

acc_task_update:
    path:     /update/{id}
    defaults: { _controller: ACCUserBundle:Task:update }
    methods:  [POST, PUT]

acc_task_view:
    path:     /view/{id}
    defaults: { _controller: ACCUserBundle:Task:view }

acc_task_delete:
    path:     /delete/{id}
    defaults: { _controller: ACCUserBundle:Task:delete }
    methods:  [POST, DELETE]

acc_task_redirect_add:
    path: /create
    defaults:
        _controller: ACCUserBundle:Task:add
        path: /add
        permanent: true

acc_task_custom:
    path:     /custom
    defaults: { _controller: ACCUserBundle:Task:custom }
    
acc_task_process:
    path:     /process/{id}
    defaults: { _controller: ACCUserBundle:Task:process }
    methods:  [POST, PUT]    

acc_task_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: ACCUserBundle:Task:edit
        path: /edit/{id}
        permanent: true