acc_user_index:
    path:     /index
    defaults: { _controller: ACCUserBundle:User:index }

acc_user_add:
    path:     /add
    defaults: { _controller: ACCUserBundle:User:add }

acc_user_create:
    path:     /create
    defaults: { _controller: ACCUserBundle:User:create }
    methods:  POST

acc_user_edit:
    path:     /edit/{id}
    defaults: { _controller: ACCUserBundle:User:edit }

acc_user_update:
    path:     /update/{id}
    defaults: { _controller: ACCUserBundle:User:update }
    methods:  [POST, PUT]

acc_user_view:
    path:     /view/{id}
    defaults: { _controller: ACCUserBundle:User:view }

acc_user_delete:
    path:     /delete/{id}
    defaults: { _controller: ACCUserBundle:User:delete }
    methods:  [POST, DELETE]

acc_user_redirect_add:
    path: /create
    defaults:
        _controller: ACCUserBundle:User:add
        path: /add
        permanent: true

acc_user_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: ACCUserBundle:User:edit
        path: /edit/{id}
        permanent: true