acc_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: ACCUserBundle:Default:index }

acc_user_index:
    path:     /user/index
    defaults: { _controller: ACCUserBundle:User:index }

acc_user_add:
    path:     /user/add
    defaults: { _controller: ACCUserBundle:User:add }

acc_user_create:
    path:     /user/create
    defaults: { _controller: ACCUserBundle:User:create }
    methods: POST

acc_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: ACCUserBundle:User:edit }

acc_user_view:
    path:     /user/view/{id}
    defaults: { _controller: ACCUserBundle:User:view }

acc_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: ACCUserBundle:User:delete }

acc_user_redirect_add:
    path:     /user/create
    defaults: 
        _controller: ACCUserBundle:User:add
        path: /user/add
        permanent: true
